FROM daocloud.io/library/tomcat:8.5.15-jre8
COPY springboot.war /usr/local/tomcat/webapps

# docker-compose.yml文件
version: "1.0"
services:
  testcd:
    build: docker
    restart: always
    container_name: testcd
    ports:
      - 8080:8080