server:
  port: 8080
spring:
  datasource:
    driverClassName:  com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.170.190/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: Mysql
    generate-ddl: true
    show-sql: true
  redis:
    database: 0
    host: 121.36.161.39
    port: 6379111
