server:
  port: 8080
spring:
  datasource:
    driverClassName:  com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 59852369
  jpa:
    database: Mysql
    generate-ddl: true
    show-sql: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123
